apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: workspace-pvc
  params:
    - name: image
      value: longmp197/go-sample-app:2020.08.05-11.25.04
    - name: repo-url
      value: https://github.com/longmp197/go-sample-app.git
    - name: revision
      value: master
  serviceAccountName: build-bot
